# Generated by Django 3.2.12 on 2022-12-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anonymized_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
